name: EStorage
version: ${project.version}
main: me.jules.estorage.EStorage
api-version: 1.20
description: Virtual storage plugin with party/invite feature.
commands:
  estorage:
    description: Open your own storage or manage invites.
    usage: /estorage [party|invite|kick|bypassip] [player]
softdepend: [PlaceholderAPI]
